name: Branch Check
run-name: Create Version Tag
on: [push]
jobs:
  find-tag-name:
     runs-on: ubuntu-latest
     outputs:
       tag_by_release_branch: ${{steps.branch.outputs.tag_by_release_branch}}
       TAG_BY_BRANCH: ${{steps.branch.outputs.tag_by_branch}}
     steps: 
      - name: Find Tag Version
      - id: tag
        uses: actions/checkout@v4
      - run: echo "Branch 1 - ${{ github.ref }}"
      - name: Find Tag Name
        uses: actions/checkout@v4
      - id: branch
        run: | 
                  BRANCH="release/1.2.3"
                  if [[ $BRANCH == release/* ]]; then
                    echo "tag_by_release_branch=${BRANCH/'release/'}" >> "$GITHUB_OUTPUT"
                    echo "Manual Tag - ${TAG_BY_RELEASE_BRANCH}"
                  elif [[ $BRANCH == release ]]; then 
                    echo "tag_by_branch=minor" >> "$GITHUB_OUTPUT"
                    echo "Release branch"
                  elif [[ $BRANCH == hotfix ]]; then 
                    echo "Hotfix branch"
                     echo "tag_by_branch=patch" >> "$GITHUB_OUTPUT"
                  else 
                    echo "Unidentified branch"
                    echo "::notice title={Unknown branch ${BRANCH}}::{Unknown branch merged to master}"
    
                  fi
          
      - run: echo "TAG_BY_RELEASE_BRANCH - ${{ env.TAG_BY_RELEASE_BRANCH }}"
      - run: echo "AUTO_INCREMENT_TAG - ${{ env.AUTO_INCREMENT_TAG }}"
      
  #Find-Tag-By-Release-Branch:
  #  name: Find Tag By Release Branch
  #  if:  ${{ jobs.find-tag-name.outputs.tag_by_release_branch }}
  #  runs-on: ubuntu-latest
    #needs: find-tag-name
  #  steps:
   #   - run: echo "===== Tag By Release version- ${{ jobs.find-tag-name.steps.tag.outputs.TAG_BY_RELEASE_BRANCH }} "

  #Find-Tag-By-Branch-Name:
  #  if:  ${{ env.TAG_BY_BRANCH }}
  #  name: Find Tag By Branch Name
   # runs-on: ubuntu-latest
   # steps: 
   #   - run: echo "===== Tag By Branch - ${{ env.TAG_BY_BRANCH }} "
      
 

        
      
