#env:
#  BRANCH_1: release
  
name: Branch Check
run-name: Create Tag
on: [push]
jobs:
  Check-Branch-Name:
     runs-on: ubuntu-latest
     steps: 
      - name: Creating Tag
        uses: actions/checkout@v4
      - run: echo "Branch 1 - ${{ github.ref }}"
      
      - name: Find Tag Name
        #if: ${{ startsWith(github.ref, 'release/') }}
        uses: actions/checkout@v4
      #- run: echo "Extract the version from the branch"
      - run: | 
            echo "Step 1"
              BRANCH="release/1.1.2"
              echo "Step 2"
              echo "Step 2 ${BRANCH}"
              if [[ $BRANCH == "release/*" ]]; then  
              echo "Step 3"
                BRANCH_TAG_VERSION="${BRANCH/'release/'}"
                echo "BRANCH_TAG_VERSION - ${BRANCH_TAG_VERSION}"
              elif [[ $BRANCH == "release" ]]; then 
              echo "Step 4"
                echo "Release branch"
              elif [[ BRANCH == "hotfix" ]]; then 
                echo "Hotfix branch"
              else 
                echo "Unidentifyed branch"
              fi
        
     # - name: Is Release Branch
     #   if: ${{ contains(github.ref, 'release') }}
     #   run: echo "Minor Version"
        
     # - name: Is Hotfix Branch
     #   if: ${{ contains(github.ref, 'hotfix') }}
     #   run: echo "Patch Version"
        
      
