name: Branch Check
run-name: Branch Check
on: [push]
jobs:
  Check-Branch-Name:
     runs-on: ubuntu-latest
     steps: 
      - name: Creating Tag
        uses: actions/checkout@v4
      - run: echo "BRANCH_NAME=release/1.23"
      - run: echo "Branch - ${BRANCH_NAME}"
      
