name: Branch Check
run-name: Create Version Tag
on: [push]
jobs:
  Find-Tag-Name:
     runs-on: ubuntu-latest
     steps: 
      - name: Find Tag Version
        uses: actions/checkout@v4
      - run: echo "Branch 1 - ${{ github.ref }}"
      
      - name: Find Tag Name
        uses: actions/checkout@v4
      - run: | 
              BRANCH="bugfix"
              if [[ $BRANCH == release/* ]]; then
                echo "TAG_BY_RELEASE_BRANCH=${BRANCH/'release/'}" >> $GITHUB_ENV
                echo "Manual Tag - ${TAG_BY_RELEASE_BRANCH}"
              elif [[ $BRANCH == release ]]; then 
                echo "TAG_BY_BRANCH=minor" >> $GITHUB_ENV
                echo "Release branch"
              elif [[ $BRANCH == hotfix ]]; then 
                echo "Hotfix branch"
                 echo "TAG_BY_BRANCH=patch" >> $GITHUB_ENV
              else 
                echo "Unidentified branch"
                echo "::notice title={Unknown branch ${BRANCH}}::{Unknown branch merged to master}"

              fi
          
      - run: echo "TAG_BY_RELEASE_BRANCH - ${{ env.TAG_BY_RELEASE_BRANCH }}"
      - run: echo "AUTO_INCREMENT_TAG - ${{ env.AUTO_INCREMENT_TAG }}"
      
  Increment-Tag-By-Release-Branch:
    if:  ${{ env.TAG_BY_RELEASE_BRANCH }}
    name: Apply Tag By Release Branch
    runs-on: ubuntu-latest
    steps: 
      - run: echo "===== Tag By Release version- ${{ env.TAG_BY_RELEASE_BRANCH }} "

  Increment-Tag-By-Branch-Name:
    if:  ${{ env.TAG_BY_BRANCH }}
    name: Increment
    runs-on: ubuntu-latest
    steps: 
      - run: echo "===== Tag By Branch - ${{ env.TAG_BY_BRANCH }} "
      
 

        
      
