name: Branch Check
run-name: Branch Check
on: [push]
jobs:
  Check-Branch-Name:
     runs-on: ubuntu-latest
     steps: 
      - name: Creating Tag
        uses: actions/checkout@v4
      - run: echo "DKA GITHUB_ACTOR (${{github.head_ref}})"
