env:
  BRANCH_TAG_VERSION: release
  AUTO_INCREMENT_TAG: minor
  
name: Branch Check
run-name: Create Version Tag
on: [push]
jobs:
  Find-Tag-Name:
     runs-on: ubuntu-latest
     steps: 
      - name: Find Tag Version
        uses: actions/checkout@v4
      - run: echo "Branch 1 - ${{ github.ref }}"
      
      - name: Find Tag Name
        #if: ${{ startsWith(github.ref, 'release/') }}
        uses: actions/checkout@v4
      #- run: echo "Extract the version from the branch"
      - run: | 
              BRANCH="bugfix"
              if [[ $BRANCH == release/* ]]; then
                echo "BRANCH_TAG_VERSION=${BRANCH/'release/'}" >> $GITHUB_ENV
                echo "BRANCH_TAG_VERSION v1 - ${BRANCH_TAG_VERSION}"
              elif [[ $BRANCH == release ]]; then 
                echo "AUTO_INCREMENT_TAG=minor" >> $GITHUB_ENV
                echo "Release branch"
              elif [[ $BRANCH == hotfix ]]; then 
                echo "Hotfix branch"
                 echo "AUTO_INCREMENT_TAG=patch" >> $GITHUB_ENV
              else 
                echo "Unidentified branch"
                echo "::notice file={name},line={line},endLine={endLine},title={Unknown branch ${BRANCH}}::{Unknown branch merged to master}"

              fi
          
      - run: echo "BRANCH_TAG_VERSION - ${{ env.BRANCH_TAG_VERSION }}"
      - run: echo "AUTO_INCREMENT_TAG - ${{ env.AUTO_INCREMENT_TAG }}"
        
     # - name: Is Release Branch
     #   if: ${{ contains(github.ref, 'release') }}
     #   run: echo "Minor Version"
        
     # - name: Is Hotfix Branch
     #   if: ${{ contains(github.ref, 'hotfix') }}
     #   run: echo "Patch Version"
        
      
