name: Branch Check
run-name: Create Version Tag
on: [push]
jobs:
  find-tag-name:
     name: Find Tag By Branch
     runs-on: ubuntu-latest
     outputs:
       release_version: ${{steps.tag.outputs.release_version}}
       release_type: ${{steps.tag.outputs.release_type}}
     steps: 
      #- name: Find Tag Version
      #  id: tag
      #  uses: actions/checkout@v4
      #- run: echo "Branch 1 - ${{ github.ref }}"
      - name: Find Tag Name
        id: tag
        run: | 
                  BRANCH="bugfix"
                  if [[ $BRANCH == release/* ]]; then
                    echo "release_version=${BRANCH/'release/'}" >> $GITHUB_OUTPUT
                  elif [[ $BRANCH == release ]]; then 
                    echo "release_type=minor" >> $GITHUB_OUTPUT
                    echo "Release branch"
                  elif [[ $BRANCH == hotfix ]]; then 
                    echo "Hotfix branch"
                     echo "release_type=patch" >> $GITHUB_OUTPUT
                  else 
                    echo "Unidentified branch"
                    echo "::notice title={Unknown branch ${BRANCH}}::{Unknown branch merged to master}"
                  fi
      #- name: Print Values              
      #  run: echo" tag_by_release_branch - ${{jobs.find-tag-name.outputs.tag_by_release_branch}}"
      
  #Tag-By-Release-Version:
  #  name: Tag By Release Branch
  #  if:  ${{ needs.find-tag-name.outputs.tag_by_release_branch }}
  #  runs-on: ubuntu-latest
  #  needs: find-tag-name
  #  steps:
  #    - env:
  #        tag_version: ${{needs.find-tag-name.outputs.release_version}}
  #      run: echo "===== Next Tag Version - $tag_version"

  Find-Next-Tag-By-Merge-Branch:
    name: Find Next Tag By Merge Branch
    if:  ${{ needs.find-tag-name.outputs.release_type }}
    runs-on: ubuntu-latest
    needs: find-tag-name
    steps:
      - env:
          release_type: ${{needs.find-tag-name.outputs.release_type}}
          
      - name: Find Next Tag For $release_type release
        uses: reecetech/version-increment@2023.10.1
        id: version
        with:
          use_api: true
          increment: $release_type
      
 

        
      
