env:
  BRANCH_TAG_VERSION: release
  AUTO_INCREMENT_TAG: minor
  
name: Branch Check
run-name: Create Version Tag
on: [push]
jobs:
  Check-Branch-Name:
     runs-on: ubuntu-latest
     steps: 
      - name: Find Tag Version
        uses: actions/checkout@v4
      - run: echo "Branch 1 - ${{ github.ref }}"
      
      - name: Find Tag Name
        #if: ${{ startsWith(github.ref, 'release/') }}
        uses: actions/checkout@v4
      #- run: echo "Extract the version from the branch"
      - run: | 
              BRANCH="release/1.1.2"
              if [[ $BRANCH == release/* ]]; then
                echo "BRANCH_TAG_VERSION=${BRANCH/'release/'}" >> $GITHUB_ENV
                echo "BRANCH_TAG_VERSION v1 - ${BRANCH_TAG_VERSION}"
              elif [[ $BRANCH == release ]]; then 
                AUTO_INCREMENT_TAG="minor"
                echo "Release branch"
              elif [[ $BRANCH == hotfix ]]; then 
                echo "Hotfix branch"
                 AUTO_INCREMENT_TAG="patch"
              else 
                echo "Unidentified branch"
              fi
          
      - run: echo "BRANCH_TAG_VERSION - ${{ env.BRANCH_TAG_VERSION }}"
      - run: echo "AUTO_INCREMENT_TAG - ${AUTO_INCREMENT_TAG}"
        
     # - name: Is Release Branch
     #   if: ${{ contains(github.ref, 'release') }}
     #   run: echo "Minor Version"
        
     # - name: Is Hotfix Branch
     #   if: ${{ contains(github.ref, 'hotfix') }}
     #   run: echo "Patch Version"
        
      
