env:
  TAG_NAME: "-"

name: Branch Check
run-name: Create Version Tag
on: [push]
jobs:
  find-tag-name:
     name: Find Tag By Branch
     runs-on: ubuntu-latest
     outputs:
       #release_version: ${{steps.tag.outputs.release_version}}
       release_type: ${{steps.tag.outputs.release_type}}
     steps: 
      #- name: Find Tag Version
      #  id: tag
      #  uses: actions/checkout@v4
      #- run: echo "Branch 1 - ${{ github.ref }}"
      - name: Find Tag Name
        id: tag
        run: | 
                  BRANCH="release"
                  if [[ $BRANCH == release/* ]]; then
                    echo "TAG_NAME=${BRANCH/'release/'}" >> $GITHUB_ENV
                  elif [[ $BRANCH == release ]]; then 
                    echo "release_type=minor" >> $GITHUB_OUTPUT
                  elif [[ $BRANCH == hotfix ]]; then 
                     echo "release_type=patch" >> $GITHUB_OUTPUT
                  else 
                    echo "Unidentified branch"
                    echo "::notice title={Unknown branch ${BRANCH}}::{Unknown branch merged to master}"
                  fi
      #- name: Print Values              
      #  run: echo" tag_by_release_branch - ${{jobs.find-tag-name.outputs.tag_by_release_branch}}"
      
  #Tag-By-Release-Version:
  #  name: Tag By Release Branch
  #  if:  ${{ needs.find-tag-name.outputs.tag_by_release_branch }}
  #  runs-on: ubuntu-latest
  #  needs: find-tag-name
  #  steps:
  #    - env:
  #        tag_version: ${{needs.find-tag-name.outputs.release_version}}
  #      run: echo "===== Next Tag Version - $tag_version"

  find-next-tag-by-merge-branch:
    name: Find Next Tag By Merge Branch
    if:  ${{ needs.find-tag-name.outputs.release_type }}
    runs-on: ubuntu-latest
    needs: find-tag-name
    steps:
      - env:
          release_type: ${{needs.find-tag-name.outputs.release_type}}
        run: echo "=====  Branch Type - ($release_type)"
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Find Next Tag
        uses: reecetech/version-increment@2023.10.1
        id: version
        with:
          use_api: true
          increment: ${{needs.find-tag-name.outputs.release_type}}

      - run: echo "Next Version inline - ${{steps.version.outputs.v-version}}"
      - run: echo "TAG_NAME=$(echo ${{steps.version.outputs.v-version}})" >> $GITHUB_ENV
      - run: echo "DKA=123456" >> $GITHUB_ENV
        env:
          TAG_NAME: ${{steps.version.outputs.v-version}}
          
  tag-branch:
    name: Tag Branch
    runs-on: ubuntu-latest
    needs: find-next-tag-by-merge-branch
    steps:
      #- run: echo "Tag Version - ${{TAG_NAME}}"
      - run: echo "Tag Version1 - ${{env.TAG_NAME}}"
      - run: echo "DKA - $DKA"
