name: Branch Check
run-name: Branch Check
on: [push]
jobs:
  Check-Branch-Name:
     runs-on: ubuntu-latest
     steps: 
      - name: Creating Tag
        uses: actions/checkout@v4
      - run: BRANCH_NAME="release/1.23"
      - run: echo "Branch 1 - ${BRANCH_NAME}"
      - run: echo "Branch 2 - ${{BRANCH_NAME}}"
      
