name: Branch Check
run-name: Branch Check
on: [push]
jobs:
  Check-Branch-Name:
     runs-on: ubuntu-latest
     steps: 
      - name: Is Tag Version In Release Branch
        id: set_branch
        run: BRANCH="release/1.2.3" >> $GITHUB_OUTPUT
        if: ${{ startsWith(steps.set_branch.outputs.BRANCH, 'release/') }}
      - run: echo "Release Branch with version"
        if: ${{ endsWith(steps.set_branch.outputs.BRANCH, 'release') }}
      - run: echo "Release Branch Minor Release"
        if: ${{ endsWith(steps.set_branch.outputs.BRANCH, 'hotfix') }}
      - run: echo "Release Branch Patch Release"
