env:
  BRANCH: release/1.2.3
  
name: Branch Check
run-name: Branch Check
on: [push]
jobs:
  find-tag-name:
     runs-on: ubuntu-latest
     outputs:
       TAG_NAME: ${{steps.tag.outputs.TAG}}
     steps: 
      - name: set Version
        id: set_branch
        run: | 
          echo BRANCH_NEW="release/1.2.3" >> $GITHUB_ENV
          echo "Branch New: ${BRANCH_NEW}"
        
      - name: Is Tag Version In Release Branch
        id: branch_tag
        if: ${{ startsWith(env.BRANCH, 'release/') }}
        run: |
            echo "Release Branch with version"
            echo "TAG_NAME=${BRANCH_NEW/'release/'}" >> $GITHUB_ENV
      - name: Is Release Branch
        if: ${{ endsWith(env.BRANCH, 'release') }}
        run: echo "Release Branch Minor Release"
      - name: Is Hotfix Branch
        if: ${{ endsWith(env.BRANCH, 'hotfix') }}
        run: echo "Release Branch Patch Release"

      - name: Printing Tag
        id: tag
        run: | 
           echo "Release TAG_NAME - ${TAG_NAME}"
           echo "TAG=${TAG_NAME}" >> $GITHUB_OUTPUT

  create-tag:
    name: Tag Branch
    runs-on: ubuntu-latest
    needs: find-tag-name
    steps:
      - run: echo "Tag TAG_NAME - ${{needs.find-tag-name.outputs.TAG_NAME}}"
           
