env:
  BRANCH: release/1.2.3
name: Branch Check
run-name: Branch Check
on: [push]
jobs:
  find-tag-in-branch:
     name: Find Tag Name In Branch
     runs-on: ubuntu-latest
     outputs:
       TAG_NAME: ${{steps.tag.outputs.TAG}}
     steps: 
      - name: set Version
        id: set_branch
        run: | 
          echo BRANCH_NEW="release/1.2.3" >> $GITHUB_ENV
          echo "Branch New: ${BRANCH_NEW}"
      - name: Is Tag Version In Release Branch
        id: branch_tag
        if: ${{ startsWith(env.BRANCH, 'release/') }}
        run: |
            echo "Release Branch with version"
            echo "TAG_NAME=${BRANCH_NEW/'release/'}" >> $GITHUB_ENV

  find-tag-by-branch:
    if:  ${{ !needs.find-tag-in-branch.outputs.TAG_NAME }}
    runs-on: ubuntu-latest
    needs: find-tag-in-branch
    steps:
      - name: Is branch wihout a version
        id: branch_release
        run: |
          if [[ $BRANCH_NEW == release ]]; then 
            echo "RELEASE_TYPE=minor" >> $GITHUB_OUTPUT
          elif [[ $BRANCH_NEW == hotfix ]]; then 
            echo "RELEASE_TYPE=patch" >> $GITHUB_OUTPUT
          fi

      - name: Initiating Next Version Lookup @
        uses: actions/checkout@v4
        if: ${{ steps.branch_release.outputs.RELEASE_TYPE }}
      - name: Find Next Tag By Branch @
        id: version
        uses: reecetech/version-increment@2023.10.1
        with:
          use_api: true
          increment: ${{ steps.branch_release.outputs.RELEASE_TYPE }}
      - run: |
          echo "Next Release - ${{steps.version.outputs.v-version}}"
           echo "TAG_NAME=${{steps.version.outputs.v-version}}" >> $GITHUB_ENV
            
      - name: Printing Tag
        id: tag
        run: | 
           echo "Release TAG_NAME - ${TAG_NAME}"
           echo "Release Version RELEASE_TYPE - ${RELEASE_TYPE}"
           echo "TAG=${TAG_NAME}" >> $GITHUB_OUTPUT
           if [[ $TAG_NAME ]]; then
              echo "TAG=${TAG_NAME}" >> $GITHUB_OUTPUT
           fi

  create-tag:
    name: Tag Branch
    runs-on: ubuntu-latest
    needs: [find-tag-in-branch, find-tag-by-branch]
    steps:
      - run: echo "Tag TAG_NAME - ${{needs.find-tag-name.outputs.TAG_NAME}}" 
      - run: echo "Tag TAG_NAME - ${TAG_NAME}" 
           
