env:
  BRANCH: release
name: Branch Check
run-name: Branch Check
on: [push]
jobs:
  find-tag-name:
     name: Find Tag Name
     runs-on: ubuntu-latest
     outputs:
       TAG_NAME: ${{steps.tag.outputs.TAG}}
     steps: 
      - name: set Version
        id: set_branch
        run: | 
          echo BRANCH_NEW="release" >> $GITHUB_ENV
          echo "Branch New: ${BRANCH_NEW}"
        
      - name: Is Tag Version In Release Branch
        id: branch_tag
        if: ${{ startsWith(env.BRANCH, 'release/') }}
        run: |
            echo "Release Branch with version"
            echo "TAG_NAME=${BRANCH_NEW/'release/'}" >> $GITHUB_ENV
      - name: Is branch wihout a version
        id: branch_release
        run: |
          echo "Checking Branch for ${BRANCH_NEW}"
          if [[ $BRANCH_NEW == release ]]; then 
            echo "RELEASE_TYPE=minor" >> $GITHUB_ENV
          elif [[ $BRANCH_NEW == hotfix ]]; then 
            echo "RELEASE_TYPE=patch" >> $GITHUB_ENV
          fi
      #- name: Is Release Branch
      #  if: ${{ endsWith(env.BRANCH, 'release') }}
      #  run: |
      #      echo "Release Branch Minor Release"
      #      echo "RELEASE_TYPE=minor" >> $GITHUB_ENV
      #- name: Is Hotfix Branch
      #  if: ${{ endsWith(env.BRANCH, 'hotfix') }}
      #  run: |
      #      echo "Release Branch Patch Release"
      #      echo "RELEASE_TYPE=patch" >> $GITHUB_ENV
  
      - run: echo " STEPPPP ${{ steps.branch_release.outputs.RELEASE_TYPE }}"
      - name: Initiating Next Version Lookup
        uses: actions/checkout@v4
        if: env.RELEASE_TYPE
      - name: Find Next Tag By Branch
        uses: reecetech/version-increment@2023.10.1
        with:
          use_api: true
          increment: ${{ steps.branch_release.outputs.RELEASE_TYPE }}
          
      - run: echo "env.RELEASE_TYPE - ${env.RELEASE_TYPE}"
      - run: echo "Next Release - ${{steps.version.outputs.v-version}}"
            
      - name: Printing Tag
        id: tag
        run: | 
           echo "Release TAG_NAME - ${TAG_NAME}"
           echo "Release Version RELEASE_TYPE - ${RELEASE_TYPE}"
           echo "TAG=${TAG_NAME}" >> $GITHUB_OUTPUT
           if [[ $TAG_NAME ]]; then
              echo "TAG=${TAG_NAME}" >> $GITHUB_OUTPUT
           fi
           

  create-tag:
    name: Tag Branch
    runs-on: ubuntu-latest
    needs: find-tag-name
    steps:
      - run: echo "Tag TAG_NAME - ${{needs.find-tag-name.outputs.TAG_NAME}}"
           
