env:
  BRANCH: release/1.2.3
  
name: Branch Check
run-name: Branch Check
on: [push]
jobs:
  Check-Branch-Name:
     runs-on: ubuntu-latest
     steps: 
      - name: set Version
      #  id: set_branch
      #  run: echo BRANCH="release/1.2.3" >> $GITHUB_ENV
        run: echo " ENV Branch - ${{env.BRANCH}}"
      - name: Is Tag Version In Release Branch
        id: branch_tag
        if: ${{ startsWith(env.BRANCH, 'release/') }}
        run: |
            echo "Release Branch with version"
            echo "Release Branch Name - env.BRANCH"
            echo "TAG_NAME=${env.BRANCH/'release/'}" >> $GITHUB_ENV
      - name: Is Release Branch
        if: ${{ endsWith(env.BRANCH, 'release') }}
        run: echo "Release Branch Minor Release"
      - name: Is Hotfix Branch
        if: ${{ endsWith(env.BRANCH, 'hotfix') }}
        run: echo "Release Branch Patch Release"

      - name: Printing Tag
        run: | 
           echo "Release BRANCH - env.BRANCH"
           echo "Release TAG_NAME - $TAG_NAME"
