name: Branch Check (Alpha)
run-name: Create Version Tag
on: [push]
jobs:
  Find-Tag-Name:
     runs-on: ubuntu-latest
     steps: 
       - uses: actions/checkout@v3
       - name: Create Release Tag
         id: release_tag
         #uses: dimuthu1982/workflow-action/release-tag@mybranch 
         uses: dimuthu1982/workflow-action/release-tag@mybranch 
         with: 
           source-branch: "hotfix/rew"
         
       - run: |
           echo "actions/release-tag"
           #echo "Output of the tag ->   ${{ steps.release_tag.outputs.tag }}"
