name: Branch Check (Beta)
run-name: Create Version Tag
on: [push]
jobs:
  Find-Tag-Name:
     runs-on: ubuntu-latest
     steps: 
       - uses: dimuthu1982/workflow-action/release-tag@main 
         with: 
           sourcebranch: "release"
         
       - run: echo "v1212"
