name: Branch Check
run-name: Create Version Tag
on: [push]
jobs:
  Find-Tag-Name:
     runs-on: ubuntu-latest
     steps: 
       - uses: workflow-action/release-tag@main 
         with: 
           source-branch: testingBranch
