name: Branch Check (Alpha)
run-name: Create Version Tag
on: [push]
jobs:
  Find-Tag-Name:
     runs-on: ubuntu-latest
     steps: 
       - name: Create Release Tag
         id: release_tag
         uses: dimuthu1982/workflow-action/release-tag@mybranch 
         with: 
           source-branch: "hotfix/rew"
         
       - run: |
           echo "v11"
           echo "Output of the tag ->   ${{ steps.release_tag.outputs.tag }}"
