name: Cleanup
run-name: Cleanup
on: [push]
jobs:
  clean-past-workflows:
     runs-on: ubuntu-latest
     steps: 
       - uses: actions/checkout@v3
       - name: Cleanup 
         id: cleanup
         uses: dimuthu1982/workflow-action/work-flow-cleanup@main
         with: 
           who-to-greet: 'Hello DKA How you doing'
         
