name: Cleanup
run-name: Cleanup
on: [push]
jobs:
  clean-past-workflows:
     runs-on: ubuntu-latest
     steps: 
       - run: |
          echo "Github Repo: ${{ github.repository }}"
       - uses: actions/checkout@v3
       - name: Cleanup 
         id: cleanup
         uses: dimuthu1982/workflow-action/work-flow-cleanup@main
         with: 
           repo-path: ${{ github.repository }}
         env:
           GH_TOKEN: ${{ github.token }}
         
